
# This file was *autogenerated* from the file attack.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_126 = Integer(126); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_65537 = Integer(65537); _sage_const_962947420735983927056946215901134429196419130606213075415963491270 = Integer(962947420735983927056946215901134429196419130606213075415963491270); _sage_const_10000 = Integer(10000); _sage_const_253 = Integer(253); _sage_const_13 = Integer(13); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_23 = Integer(23); _sage_const_7 = Integer(7); _sage_const_19 = Integer(19)#Authors: Daniel J. Bernstein and Tanja Lange
#Origin:
from sage.doctest.util import Timer
# from sage.all import var

t = Timer()

L = _sage_const_962947420735983927056946215901134429196419130606213075415963491270 
# L *= 701 # if 701 is included
print 'factors are', factor(L)
g = Mod(_sage_const_65537 ,L)

pmin = _sage_const_3 *_sage_const_2 **_sage_const_126 
pmax = _sage_const_4 *_sage_const_2 **_sage_const_126 

t.start()
x = randrange(L)
u = lift(g**randrange(L))
while True:
  p = u + randrange(ceil(pmin/L),floor(pmax/L)) * L
  if p.is_prime(): print 'p',p ;break
print 'time for first prime',t.stop().cputime
print 'u',u
t.start()
u = lift(g**randrange(L))
while True:
  q = u + randrange(ceil(pmin/L),floor(pmax/L)) * L
  if q.is_prime(): print 'q',q ;break
print 'time for second prime',t.stop().cputime

n = p * q
# print 'kdshfdglkglgtkl',log(p*q)
# n=19920726839070815994998091093341971896358011164873513502252068165898094300547540292355376641783342604056684238872899431321736308213487545942014350950815359041644853865113261438495021685898037777675661465630271412797099783047138041003690144583180000881213443421779202855681661055259092513193388583127872981726859546745771237224182179841241761252421057745479598947549253560288134249980235300420902573907076048126110226066015101444470870185069166904393225123156478224554196871078974124493506357070691906706621812669657437944813699547511830671563781996836773347584294392459515072831363041501254474779301029958385193495057
# n = int("13965a4642b9d88f507ac4223792f8edd0670f302a490523e2f2b616f7a284e849d5fc55193aa76dc4499ac194b410ebdd0bf82448120e062f69769c6384d3d701b60b3ab06adc1bb2f296ad726aa0ce7ba03b2288c02884cba3d341b8c8e8600f492b52fc7d500567ea4e50f3fa16559d7b3cf0db31ab0c751d233b61e5d2c5ab8cc4c4f6f99e3ae5c62196921821b4e6f1ff1fea0aa8015743070015707a2f795ce4d203b423c9f93f65527b5eb6d4f0c8ffb61d747382c2e56969fe23eaaf471ef79e6bc272bb0aa2ff39f649ab6327e627f4dca5b2a4c75269d561d64e039108d25aa35e6638048f488344f74d0799490096e9f47014f7fa9c15717d5b11f",16)
print 'public key',n

smooth = _sage_const_2 **_sage_const_7 *_sage_const_3 **_sage_const_3 *_sage_const_5 **_sage_const_2 *_sage_const_7 *_sage_const_11 *_sage_const_13 *_sage_const_17 *_sage_const_19 *_sage_const_23 
print 'smooth',smooth
def smoothorder(l):
  return smooth % Mod(g,l).multiplicative_order() == _sage_const_0 
# print 'order1',g.multiplicative_order()
# print 'g is',g.multiplicative_order(), lift(g^g.multiplicative_order())
v = prod(l for l,e in factor(L) if smoothorder(l))
g = Mod(g,v)
order2 = g.multiplicative_order()
print 'order2',order2
order2 = order2
# print 'v ',v
# print 'L/v',L/v,factor(L/v)
# print 'factors are',factor(v)
# p = int("c93808a77a3e282b36a80d274d4d2d8d0497815cef52e12adedb1167aa3a2027938c6ac1e39adf74aa881934dee63e0291a93d040f06b19381f99991cc50b91075ec586f023d86a6ef4cb72853f155942b54cab979176ab290922cebe33199b1ab3bf5d035b933153f6b77914c17402026e6f668469f16c59528d9dbbc423b49",16)
u = Mod(p,v)
print 'u',u
u=int(u)
# u = 117186365649536878271017440711195586067867603549008793949993871455663672155382024627758506969061973692250761281716333265235764727839244690128219862454077941750864265653024596713

print 'p residue class',(p-u)/v
print 'Start loop'
print 'order2 ',order2 
for i in range(_sage_const_10000 ):
  print i
  for j in range(i*order2,(i+_sage_const_1 )*order2):
  # print i
    x = lift(g**i)
    if(x==u):
      print 'found',x
      break
print 'End loop'

t.start()

H = _sage_const_10  + _sage_const_2 **_sage_const_253  // v
u += floor((_sage_const_7 *_sage_const_2 **_sage_const_253 ) // v) * v

w = lift(_sage_const_1 /Mod(v,n))

R = QQ['x']; (x,) = R._first_ngens(1)
f = (w*u+H*x)/n
g = H*x

k = _sage_const_3 
m = _sage_const_7 
print 'multiplicity',k
print 'lattice rank',m

basis = [f**j for j in range(_sage_const_0 ,k)] + [f**k*g**j for j in range(m-k)]
basis = [b*n**k for b in basis]
basis = [b.change_ring(ZZ) for b in basis]

M = matrix(m)
for i in range(m):
  M[i] = basis[i].coefficients(sparse=False) + [_sage_const_0 ]*(m-_sage_const_1 -i)
print 'time for creating matrix',t.stop().cputime

t.start()
# print '---',M
M = M.LLL()
print 'time for basis reduction',t.stop().cputime

Q = sum(z*(x/H)**i for i,z in enumerate(M[_sage_const_0 ]))
print(Q.roots())
# polyn=sum([x^2,-2*x,1])
# print 'poly roots',polyn.roots()
for r,multiplicity in Q.roots():
  print 'root is',r
  if u+v*r > _sage_const_0 :
    g = gcd(n,u+v*r)
    if g > _sage_const_1 : print 'successful factorization',[g,n/g]

